name: "SemVer Label Checker"
on:
  pull_request:
    types:
      - reopened
      - labeled
      - unlabeled
jobs:
  check_labels:
    name: "Check PR Labels"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mheap/github-action-required-labels@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "version major, version minor, version patch, version none"
